#
# Build configuration for Circle CI
#
version: 2

general:
    artifacts:/Users/kartik/MobileAppAutomationTest/AndroidDemo/app/build/outputs/apk//home/ubuntu/your-app-name/app/build/outputs/apk/

machine:
    environment:
        ANDROID_HOME: /Users/kartik/Library/Android/sdk

dependencies:
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-25.0.3,android-25,extra-google-m2repository,extra-google-google_play_services,extra-android-support
        - ANDROID_HOME=/Users/kartik/Library/Android/sdk ./gradlew dependencies

test:
    override:
        - (./gradlew assemble):
            timeout: 360